# Generated by Django 5.2.14 on 2026-06-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
