# Generated by Django 5.2.14 on 2026-06-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_remove_customer_orders_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
